name: formatting

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - "1.64.0"
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_deps
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt
      - run: cargo fmt -- --check

  lint:
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - "1.64.0"
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_deps
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - run: cargo clippy --all-targets --all-features -- -D clippy::pedantic
