name: Integration

permissions:
  contents: read
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  integration:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}  # Only run if the build succeeded
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - nightly
          - "1.80.0"
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        features:
         # - "libei,wayland,xdo,x11rb"
          - "default"
         # - "libei"
         # - "wayland"
          - "xdo"
          - "x11rb"
        exclude:
         # - platform: windows-latest
         #   features: "libei,wayland,xdo,x11rb"
         # - platform: windows-latest
         #   features: "libei"
         # - platform: windows-latest
         #   features: "wayland"
          - platform: windows-latest
            features: "xdo"
          - platform: windows-latest
            features: "x11rb"
         # - platform: macos-latest
         #   features: "libei,wayland,xdo,x11rb"
         # - platform: macos-latest
         #   features: "libei"
         # - platform: macos-latest
         #   features: "wayland"
          - platform: macos-latest
            features: "xdo"
          - platform: macos-latest
            features: "x11rb"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          # If manually triggered, use the current commit (GITHUB_SHA), otherwise use the head_sha from the Build workflow
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
      - uses: ./.github/actions/install_deps
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Setup headless display for tests on Linux
        if: runner.os == 'Linux' # This step is only needed on Linux. The other OSs don't need to be set up
        uses: ./.github/actions/headless_display

      - name: Run integration tests in release mode
        if: matrix.features != 'wayland' && matrix.features != 'libei' && matrix.features != 'libei,wayland,xdo,x11rb' # On Linux, the integration tests only work with X11 for now
        run: cargo test integration --release --no-default-features --features ${{ matrix.features }} -- --test-threads=1 --nocapture --include-ignored

      - name: Take screenshot
        if: always() && runner.os != 'macOS'
        uses: ./.github/actions/screenshot
        with:
          platform: ${{ matrix.platform }}
          rust: ${{ matrix.rust }}
          feature: ${{ matrix.features }}
